version: "3.7"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    expose:
      - 5433
    ports:
      - "5433:5433"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    command: -p 5433